#!/usr/bin/env python3
"""Generate texlive-full/theme.css: Overleaf's brand-green tokens remapped to the TeXnest palette.

Usage: python3 branding/make_theme.py --primary '#2F5F9E' --accent '#F2A541' [--out texlive-full/theme.css]
The file is appended to Overleaf's stylesheets when the image is built (./texnest build-texlive).
"""
import argparse
import colorsys
from pathlib import Path


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(c))) for c in rgb)


def shade(h, lightness, sat_scale=1.0):
    """Same hue as h, with the given lightness (0-1); saturation scaled for tints."""
    r, g, b = (c / 255 for c in hex_to_rgb(h))
    hue, lig, sat = colorsys.rgb_to_hls(r, g, b)
    return rgb_to_hex(tuple(c * 255 for c in colorsys.hls_to_rgb(hue, lightness, min(1, sat * sat_scale))))


def build(primary, accent):
    r, g, b = (c / 255 for c in hex_to_rgb(primary))
    _, lig, _ = colorsys.rgb_to_hls(r, g, b)
    d = lambda delta: max(0.08, min(0.92, lig + delta))  # noqa: E731
    # Overleaf's legacy scale (10 = lightest tint, 50 = brand, 70 = darkest)
    legacy = {10: shade(primary, 0.96, 0.6), 15: shade(primary, 0.92, 0.7), 20: shade(primary, 0.84, 0.8),
              30: shade(primary, 0.70), 40: shade(primary, 0.56), 50: primary,
              60: shade(primary, d(-0.08)), 65: shade(primary, d(-0.11)), 70: shade(primary, d(-0.15))}
    # Overleaf's newer design-system scale (50 = lightest, 950 = darkest)
    ds = {50: shade(primary, 0.97, 0.5), 100: shade(primary, 0.94, 0.6), 200: shade(primary, 0.86, 0.7),
          300: shade(primary, 0.74), 400: shade(primary, 0.60), 500: primary, 600: shade(primary, d(-0.06)),
          700: shade(primary, d(-0.10)), 800: shade(primary, d(-0.16)), 900: shade(primary, d(-0.24)),
          950: shade(primary, d(-0.32))}
    p, p60, p70 = primary, legacy[60], legacy[70]
    rgb = ", ".join(str(c) for c in hex_to_rgb(primary))
    lines = [f"/* TeXnest theme, generated by branding/make_theme.py --primary {primary} --accent {accent}. */",
             ":root, [data-theme=default], [data-theme=light], [data-theme=dark] {"]
    lines += [f"  --green-{k}: {v};" for k, v in legacy.items()]
    lines += [f"  --ds-color-green-{k}: {v};" for k, v in ds.items()]
    lines += [f"  --bs-primary: {p}; --bs-primary-rgb: {rgb};",
              f"  --bs-link-color: {p60}; --bs-link-color-rgb: {', '.join(str(c) for c in hex_to_rgb(p60))};",
              f"  --bs-link-hover-color: {p70}; --bs-link-hover-color-rgb: {', '.join(str(c) for c in hex_to_rgb(p70))};",
              f"  --texnest-accent: {accent};",
              "  /* success stays green so status is not confused with the brand */",
              "  --content-positive: #2e7d32; --content-positive-dark: #6cc070;",
              "}",
              "/* components that hard-code Overleaf's green */",
              f".form-check-input:checked, .form-check-input[type=checkbox]:indeterminate {{ background-color: {p}; border-color: {p}; }}",
              f".form-range::-webkit-slider-thumb {{ background-color: {p}; }}",
              f".form-range::-moz-range-thumb {{ background-color: {p}; }}",
              f".btn-outline-primary {{ --bs-btn-color: {p}; --bs-btn-border-color: {p}; --bs-btn-hover-bg: {p}; --bs-btn-hover-border-color: {p};"
              f" --bs-btn-active-bg: {p60}; --bs-btn-active-border-color: {p60}; --bs-btn-disabled-color: {p}; --bs-btn-disabled-border-color: {p}; }}",
              f".uppy-Dashboard-AddFiles-title button.uppy-Dashboard-browse {{ --bs-btn-bg: {p}; --bs-btn-border-color: {p}; --bs-btn-hover-bg: {p60};"
              f" --bs-btn-hover-border-color: {p60}; --bs-btn-active-bg: {p70}; --bs-btn-active-border-color: {p70}; --bs-btn-disabled-bg: {p}; --bs-btn-disabled-border-color: {p}; }}",
              "/* the accent is reserved for small highlights */",
              ".beta-badge, .labs-badge, .labs-opt-in-wrapper .labs-icon { background-color: var(--texnest-accent); color: #1b222c; }",
              ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--primary", required=True, help="brand color for buttons and links, e.g. '#2F5F9E'")
    ap.add_argument("--accent", required=True, help="highlight color, e.g. '#F2A541'")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parent.parent / "texlive-full" / "theme.css"))
    a = ap.parse_args()
    for h in (a.primary, a.accent):
        if len(h.lstrip("#")) != 6:
            ap.error(f"{h} is not a 6-digit hex color")
    css = build(a.primary.lower(), a.accent.lower())
    Path(a.out).write_text(css)
    print(f"wrote {a.out} ({len(css.splitlines())} lines) for primary {a.primary}, accent {a.accent}")


if __name__ == "__main__":
    main()
